### ISSUE TITLE
removal of user defined if...end statements

### ISSUE THREAD

**Issue by andrewbenton** [rastersoft/autovala#41]
When placing if...end statements into the .avprj file, they will be removed after re-running 'autovala update'.  This seems to occur regardless of where the if...end statment is placed.

**Comment by rastersoft** [comment]
Be careful: if the statements inside the if...end are optional (starts with an asterisk), of course they will be removed.

**Comment by rastersoft** [comment]
Is that your case?

**Comment by rastersoft** [comment]
Ok, I wasn't sure when I answered your question, but now I checked and no: all the optional statements inside an "if" are converted to manual ones, so it seems that there is something incorrect here. Check if those statements are moved to other part of the file (since the internal statements are changed from automatic to manual ones, they will be put before all the automatic ones).

**Comment by andrewbenton** [comment]
I was able to recreate the problem.  The problem occurs when the if...else is used between the defines and the vala_binary / vala_library statements.  The relevant snippet of my file was as follows:

> define: USE_ICC
> define: DEBUG

> if USE_ICC
> binary_dependency: icc
> end

> vala_binary: src/emip
> if USE_ICC
> compile_options: -g --cc=icc
> else
> compile_options: -g
> end

The first if...end block was removed when I ran `autovala update`, but caused no errors with an `autovala cmake`.  The if...end block under vala_binary remained through an `autovala update`.

**Comment by rastersoft** [comment]
Mmm... I'll check the code, but maybe "binary_dependency" doesn't support conditionals.

**Comment by rastersoft** [comment]
Ok, the reason is that "autovala deb" or "autovala rpm", which are the commands where "binary_dependency" makes sense, doesn't depend on cmake, which is the program that understand the DEFINEs. That's why the conditionals are removed: because they won't be honored.
