### ISSUE TITLE
Compilation terminated: fatal error: readline/readline.h: No such file or directory

### ISSUE THREAD

**Issue by ztefn** [rastersoft/autovala#43]
Autovala itself seems unable to compile. I'm running Ubuntu-GNOME 14.10 with Gnome 3.14 via gnome3-staging PPA.

stephen@ubuntu:~$ git clone https://github.com/rastersoft/autovala.git
Cloning into 'autovala'...
remote: Counting objects: 3933, done.
remote: Total 3933 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (3933/3933), 1.31 MiB | 580.00 KiB/s, done.
Resolving deltas: 100% (2728/2728), done.
Checking connectivity... done.
stephen@ubuntu:~$ cd /home/stephen/autovala
stephen@ubuntu:~/autovala$ mkdir install
stephen@ubuntu:~/autovala$ cd install
stephen@ubuntu:~/autovala/install$ cmake ..
-- Found Vala: /usr/bin/valac  
-- checking for Vala version of valac-0.20
-- checking for a minimum Vala version of 0.20
--   found Vala, version 0.26
-- checking for Vala version of valac-0.20
-- checking for a minimum Vala version of 0.20
--   found Vala, version 0.26
-- checking for Vala version of valac-0.20
-- checking for a minimum Vala version of 0.20
--   found Vala, version 0.26
-- Configuring done
-- Generating done
-- Build files have been written to: /home/stephen/autovala/install
stephen@ubuntu:~/autovala/install$ make
Scanning dependencies of target i18n
[  2%] messages.”
[  2%] Built target i18n
[  4%] Generating /home/stephen/autovala/install/src/autovalaLib/Config.c;autovalaLib.c;conditionalText.c;configuration.c;elementBDepend.c;elementBase.c;elementBashCompletion.c;elementBinary.c;elementCustom.c;elementDBus.c;elementData.c;elementDefine.c;elementDesktop.c;elementDoc.c;elementEosPlug.c;elementGlade.c;elementGlobal.c;elementIcon.c;elementIgnore.c;elementInclude.c;elementManpage.c;elementPixmap.c;elementPo.c;elementSDepend.c;elementScheme.c;elementValaBinary.c;findVala.c;genVapis.c;globals.c;packages.c;packages_deb.c;packages_rpm.c;readPkgconfig.c;AutoVala.vapi;AutoVala.h
/home/stephen/autovala/src/autovalaLib/packages.vala:553.5-553.38: warning: unhandled error `GLib.Error'
				file.make_directory_with_parents();
				^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/home/stephen/autovala/src/autovalaLib/packages.vala:557.5-557.17: warning: unhandled error `GLib.Error'
				file.delete();
				^^^^^^^^^^^^^
/home/stephen/autovala/src/autovalaLib/packages_deb.vala:278.6-278.21: warning: unhandled error `GLib.Error'
					f_rules.delete();
					^^^^^^^^^^^^^^^^
/home/stephen/autovala/src/autovalaLib/packages_deb.vala:315.5-315.20: warning: unhandled error `GLib.Error'
				f_rules.delete();
				^^^^^^^^^^^^^^^^
/home/stephen/autovala/src/autovalaLib/packages_deb.vala:350.5-350.20: warning: unhandled error `GLib.Error'
				f_rules.delete();
				^^^^^^^^^^^^^^^^
/home/stephen/autovala/src/autovalaLib/packages_deb.vala:385.5-385.20: warning: unhandled error `GLib.Error'
				f_rules.delete();
				^^^^^^^^^^^^^^^^
/home/stephen/autovala/src/autovalaLib/packages_deb.vala:420.5-420.20: warning: unhandled error `GLib.Error'
				f_rules.delete();
				^^^^^^^^^^^^^^^^
/home/stephen/autovala/src/autovalaLib/packages_deb.vala:441.36-441.54: warning: unhandled error `GLib.Error'
				var dis = new DataInputStream (f_changelog.read ());
				                               ^^^^^^^^^^^^^^^^^^^
/home/stephen/autovala/src/autovalaLib/packages_deb.vala:443.20-443.39: warning: unhandled error `GLib.IOError'
				while ((line = dis.read_line (null)) != null) {
				               ^^^^^^^^^^^^^^^^^^^^
/home/stephen/autovala/src/autovalaLib/packages_deb.vala:471.5-471.15: warning: unhandled error `GLib.IOError'
				dis.close();
				^^^^^^^^^^^
/home/stephen/autovala/src/autovalaLib/packages_deb.vala:472.5-472.24: warning: unhandled error `GLib.Error'
				f_changelog.delete();
				^^^^^^^^^^^^^^^^^^^^
/home/stephen/autovala/src/autovalaLib/packages_deb.vala:567.5-567.24: warning: unhandled error `GLib.Error'
				f_changelog.delete();
				^^^^^^^^^^^^^^^^^^^^
/home/stephen/autovala/src/autovalaLib/packages.vala:70.3-70.25: warning: method `AutoVala.packages.show_errors' never used
		public void show_errors() {
		^^^^^^^^^^^^^^^^^^^^^^^
/home/stephen/autovala/src/autovalaLib/packages.vala:371.21-371.59: warning: local variable `not_found' declared but never used
			Gee.List<string> not_found = new Gee.ArrayList<string>();
			                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/home/stephen/autovala/src/autovalaLib/packages.vala:590.8-590.11: warning: local variable `pos2' declared but never used
			int pos2;
			    ^^^^
/home/stephen/autovala/src/autovalaLib/packages.vala:687.10-687.28: warning: local variable `with_spaces' declared but never used
				bool with_spaces = false;
				     ^^^^^^^^^^^^^^^^^^^
/home/stephen/autovala/src/autovalaLib/packages_deb.vala:127.13-127.25: warning: local variable `last_key' declared but never used
					string last_key = "";
					       ^^^^^^^^^^^^^
/home/stephen/autovala/src/autovalaLib/packages_rpm.vala:110.11-110.23: warning: local variable `source' declared but never used
					bool source = true;
					     ^^^^^^^^^^^^^
/home/stephen/autovala/src/autovalaLib/packages_rpm.vala:166.10-166.18: warning: local variable `not_first' declared but never used
				bool not_first;
				     ^^^^^^^^^
Compilation succeeded - 19 warning(s)
Scanning dependencies of target AutoVala
[  6%] Building C object src/autovalaLib/CMakeFiles/AutoVala.dir/Config.c.o
[  8%] Building C object src/autovalaLib/CMakeFiles/AutoVala.dir/autovalaLib.c.o
[ 10%] Building C object src/autovalaLib/CMakeFiles/AutoVala.dir/conditionalText.c.o
[ 13%] Building C object src/autovalaLib/CMakeFiles/AutoVala.dir/configuration.c.o
In file included from /usr/include/glib-2.0/glib.h:79:0,
                 from /home/stephen/autovala/install/src/autovalaLib/configuration.c:22:
/home/stephen/autovala/install/src/autovalaLib/configuration.c: In function ‘string_strip’:
/home/stephen/autovala/install/src/autovalaLib/configuration.c:1056:14: warning: passing argument 1 of ‘g_strchug’ discards ‘const’ qualifier from pointer target type
  g_strstrip (_tmp1_);
              ^
/usr/include/glib-2.0/glib/gstrfuncs.h:180:53: note: in definition of macro ‘g_strstrip’
 #define g_strstrip( string ) g_strchomp (g_strchug (string))
                                                     ^
/usr/include/glib-2.0/glib/gstrfuncs.h:175:23: note: expected ‘gchar *’ but argument is of type ‘const gchar *’
 gchar*                g_strchug        (gchar        *string);
                       ^
[ 15%] Building C object src/autovalaLib/CMakeFiles/AutoVala.dir/elementBDepend.c.o
In file included from /usr/include/glib-2.0/glib.h:79:0,
                 from /home/stephen/autovala/install/src/autovalaLib/elementBDepend.c:22:
/home/stephen/autovala/install/src/autovalaLib/elementBDepend.c: In function ‘string_strip’:
/home/stephen/autovala/install/src/autovalaLib/elementBDepend.c:316:14: warning: passing argument 1 of ‘g_strchug’ discards ‘const’ qualifier from pointer target type
  g_strstrip (_tmp1_);
              ^
/usr/include/glib-2.0/glib/gstrfuncs.h:180:53: note: in definition of macro ‘g_strstrip’
 #define g_strstrip( string ) g_strchomp (g_strchug (string))
                                                     ^
/usr/include/glib-2.0/glib/gstrfuncs.h:175:23: note: expected ‘gchar *’ but argument is of type ‘const gchar *’
 gchar*                g_strchug        (gchar        *string);
                       ^
[ 17%] Building C object src/autovalaLib/CMakeFiles/AutoVala.dir/elementBase.c.o
In file included from /usr/include/glib-2.0/glib.h:79:0,
                 from /home/stephen/autovala/install/src/autovalaLib/elementBase.c:22:
/home/stephen/autovala/install/src/autovalaLib/elementBase.c: In function ‘string_strip’:
/home/stephen/autovala/install/src/autovalaLib/elementBase.c:1053:14: warning: passing argument 1 of ‘g_strchug’ discards ‘const’ qualifier from pointer target type
  g_strstrip (_tmp1_);
              ^
/usr/include/glib-2.0/glib/gstrfuncs.h:180:53: note: in definition of macro ‘g_strstrip’
 #define g_strstrip( string ) g_strchomp (g_strchug (string))
                                                     ^
/usr/include/glib-2.0/glib/gstrfuncs.h:175:23: note: expected ‘gchar *’ but argument is of type ‘const gchar *’
 gchar*                g_strchug        (gchar        *string);
                       ^
[ 19%] Building C object src/autovalaLib/CMakeFiles/AutoVala.dir/elementBashCompletion.c.o
[ 21%] Building C object src/autovalaLib/CMakeFiles/AutoVala.dir/elementBinary.c.o
[ 23%] Building C object src/autovalaLib/CMakeFiles/AutoVala.dir/elementCustom.c.o
In file included from /usr/include/glib-2.0/glib.h:79:0,
                 from /home/stephen/autovala/install/src/autovalaLib/elementCustom.c:22:
/home/stephen/autovala/install/src/autovalaLib/elementCustom.c: In function ‘string_strip’:
/home/stephen/autovala/install/src/autovalaLib/elementCustom.c:400:14: warning: passing argument 1 of ‘g_strchug’ discards ‘const’ qualifier from pointer target type
  g_strstrip (_tmp1_);
              ^
/usr/include/glib-2.0/glib/gstrfuncs.h:180:53: note: in definition of macro ‘g_strstrip’
 #define g_strstrip( string ) g_strchomp (g_strchug (string))
                                                     ^
/usr/include/glib-2.0/glib/gstrfuncs.h:175:23: note: expected ‘gchar *’ but argument is of type ‘const gchar *’
 gchar*                g_strchug        (gchar        *string);
                       ^
[ 26%] Building C object src/autovalaLib/CMakeFiles/AutoVala.dir/elementDBus.c.o
[ 28%] Building C object src/autovalaLib/CMakeFiles/AutoVala.dir/elementData.c.o
[ 30%] Building C object src/autovalaLib/CMakeFiles/AutoVala.dir/elementDefine.c.o
In file included from /usr/include/glib-2.0/glib.h:79:0,
                 from /home/stephen/autovala/install/src/autovalaLib/elementDefine.c:22:
/home/stephen/autovala/install/src/autovalaLib/elementDefine.c: In function ‘string_strip’:
/home/stephen/autovala/install/src/autovalaLib/elementDefine.c:337:14: warning: passing argument 1 of ‘g_strchug’ discards ‘const’ qualifier from pointer target type
  g_strstrip (_tmp1_);
              ^
/usr/include/glib-2.0/glib/gstrfuncs.h:180:53: note: in definition of macro ‘g_strstrip’
 #define g_strstrip( string ) g_strchomp (g_strchug (string))
                                                     ^
/usr/include/glib-2.0/glib/gstrfuncs.h:175:23: note: expected ‘gchar *’ but argument is of type ‘const gchar *’
 gchar*                g_strchug        (gchar        *string);
                       ^
[ 32%] Building C object src/autovalaLib/CMakeFiles/AutoVala.dir/elementDesktop.c.o
In file included from /usr/include/glib-2.0/glib.h:79:0,
                 from /home/stephen/autovala/install/src/autovalaLib/elementDesktop.c:22:
/home/stephen/autovala/install/src/autovalaLib/elementDesktop.c: In function ‘string_strip’:
/home/stephen/autovala/install/src/autovalaLib/elementDesktop.c:414:14: warning: passing argument 1 of ‘g_strchug’ discards ‘const’ qualifier from pointer target type
  g_strstrip (_tmp1_);
              ^
/usr/include/glib-2.0/glib/gstrfuncs.h:180:53: note: in definition of macro ‘g_strstrip’
 #define g_strstrip( string ) g_strchomp (g_strchug (string))
                                                     ^
/usr/include/glib-2.0/glib/gstrfuncs.h:175:23: note: expected ‘gchar *’ but argument is of type ‘const gchar *’
 gchar*                g_strchug        (gchar        *string);
                       ^
[ 34%] Building C object src/autovalaLib/CMakeFiles/AutoVala.dir/elementDoc.c.o
[ 36%] Building C object src/autovalaLib/CMakeFiles/AutoVala.dir/elementEosPlug.c.o
[ 39%] Building C object src/autovalaLib/CMakeFiles/AutoVala.dir/elementGlade.c.o
[ 41%] Building C object src/autovalaLib/CMakeFiles/AutoVala.dir/elementGlobal.c.o
/home/stephen/autovala/install/src/autovalaLib/elementGlobal.c: In function ‘auto_vala_element_global_generateMainCMakeHeader’:
/home/stephen/autovala/install/src/autovalaLib/elementGlobal.c:1608:43: warning: passing argument 1 of ‘gee_abstract_map_get_keys’ from incompatible pointer type
     _tmp295_ = gee_abstract_map_get_keys ((GeeMap*) _tmp294_);
                                           ^
In file included from /home/stephen/autovala/install/src/autovalaLib/elementGlobal.c:27:0:
/usr/include/gee-0.8/gee.h:1456:9: note: expected ‘struct GeeAbstractMap *’ but argument is of type ‘struct GeeMap *’
 GeeSet* gee_abstract_map_get_keys (GeeAbstractMap* self);
         ^
/home/stephen/autovala/install/src/autovalaLib/elementGlobal.c:1868:44: warning: passing argument 1 of ‘gee_abstract_map_get_keys’ from incompatible pointer type
      _tmp373_ = gee_abstract_map_get_keys ((GeeMap*) _tmp372_);
                                            ^
In file included from /home/stephen/autovala/install/src/autovalaLib/elementGlobal.c:27:0:
/usr/include/gee-0.8/gee.h:1456:9: note: expected ‘struct GeeAbstractMap *’ but argument is of type ‘struct GeeMap *’
 GeeSet* gee_abstract_map_get_keys (GeeAbstractMap* self);
         ^
[ 43%] Building C object src/autovalaLib/CMakeFiles/AutoVala.dir/elementIcon.c.o
In file included from /usr/include/glib-2.0/glib.h:79:0,
                 from /home/stephen/autovala/install/src/autovalaLib/elementIcon.c:22:
/home/stephen/autovala/install/src/autovalaLib/elementIcon.c: In function ‘string_strip’:
/home/stephen/autovala/install/src/autovalaLib/elementIcon.c:448:14: warning: passing argument 1 of ‘g_strchug’ discards ‘const’ qualifier from pointer target type
  g_strstrip (_tmp1_);
              ^
/usr/include/glib-2.0/glib/gstrfuncs.h:180:53: note: in definition of macro ‘g_strstrip’
 #define g_strstrip( string ) g_strchomp (g_strchug (string))
                                                     ^
/usr/include/glib-2.0/glib/gstrfuncs.h:175:23: note: expected ‘gchar *’ but argument is of type ‘const gchar *’
 gchar*                g_strchug        (gchar        *string);
                       ^
[ 45%] Building C object src/autovalaLib/CMakeFiles/AutoVala.dir/elementIgnore.c.o
In file included from /usr/include/glib-2.0/glib.h:79:0,
                 from /home/stephen/autovala/install/src/autovalaLib/elementIgnore.c:22:
/home/stephen/autovala/install/src/autovalaLib/elementIgnore.c: In function ‘string_strip’:
/home/stephen/autovala/install/src/autovalaLib/elementIgnore.c:294:14: warning: passing argument 1 of ‘g_strchug’ discards ‘const’ qualifier from pointer target type
  g_strstrip (_tmp1_);
              ^
/usr/include/glib-2.0/glib/gstrfuncs.h:180:53: note: in definition of macro ‘g_strstrip’
 #define g_strstrip( string ) g_strchomp (g_strchug (string))
                                                     ^
/usr/include/glib-2.0/glib/gstrfuncs.h:175:23: note: expected ‘gchar *’ but argument is of type ‘const gchar *’
 gchar*                g_strchug        (gchar        *string);
                       ^
[ 47%] Building C object src/autovalaLib/CMakeFiles/AutoVala.dir/elementInclude.c.o
[ 50%] Building C object src/autovalaLib/CMakeFiles/AutoVala.dir/elementManpage.c.o
In file included from /usr/include/glib-2.0/glib.h:79:0,
                 from /home/stephen/autovala/install/src/autovalaLib/elementManpage.c:22:
/home/stephen/autovala/install/src/autovalaLib/elementManpage.c: In function ‘string_strip’:
/home/stephen/autovala/install/src/autovalaLib/elementManpage.c:532:14: warning: passing argument 1 of ‘g_strchug’ discards ‘const’ qualifier from pointer target type
  g_strstrip (_tmp1_);
              ^
/usr/include/glib-2.0/glib/gstrfuncs.h:180:53: note: in definition of macro ‘g_strstrip’
 #define g_strstrip( string ) g_strchomp (g_strchug (string))
                                                     ^
/usr/include/glib-2.0/glib/gstrfuncs.h:175:23: note: expected ‘gchar *’ but argument is of type ‘const gchar *’
 gchar*                g_strchug        (gchar        *string);
                       ^
[ 52%] Building C object src/autovalaLib/CMakeFiles/AutoVala.dir/elementPixmap.c.o
[ 54%] Building C object src/autovalaLib/CMakeFiles/AutoVala.dir/elementPo.c.o
[ 56%] Building C object src/autovalaLib/CMakeFiles/AutoVala.dir/elementSDepend.c.o
In file included from /usr/include/glib-2.0/glib.h:79:0,
                 from /home/stephen/autovala/install/src/autovalaLib/elementSDepend.c:22:
/home/stephen/autovala/install/src/autovalaLib/elementSDepend.c: In function ‘string_strip’:
/home/stephen/autovala/install/src/autovalaLib/elementSDepend.c:316:14: warning: passing argument 1 of ‘g_strchug’ discards ‘const’ qualifier from pointer target type
  g_strstrip (_tmp1_);
              ^
/usr/include/glib-2.0/glib/gstrfuncs.h:180:53: note: in definition of macro ‘g_strstrip’
 #define g_strstrip( string ) g_strchomp (g_strchug (string))
                                                     ^
/usr/include/glib-2.0/glib/gstrfuncs.h:175:23: note: expected ‘gchar *’ but argument is of type ‘const gchar *’
 gchar*                g_strchug        (gchar        *string);
                       ^
[ 58%] Building C object src/autovalaLib/CMakeFiles/AutoVala.dir/elementScheme.c.o
[ 60%] Building C object src/autovalaLib/CMakeFiles/AutoVala.dir/elementValaBinary.c.o
In file included from /usr/include/glib-2.0/glib.h:79:0,
                 from /home/stephen/autovala/install/src/autovalaLib/elementValaBinary.c:22:
/home/stephen/autovala/install/src/autovalaLib/elementValaBinary.c: In function ‘string_strip’:
/home/stephen/autovala/install/src/autovalaLib/elementValaBinary.c:2822:14: warning: passing argument 1 of ‘g_strchug’ discards ‘const’ qualifier from pointer target type
  g_strstrip (_tmp1_);
              ^
/usr/include/glib-2.0/glib/gstrfuncs.h:180:53: note: in definition of macro ‘g_strstrip’
 #define g_strstrip( string ) g_strchomp (g_strchug (string))
                                                     ^
/usr/include/glib-2.0/glib/gstrfuncs.h:175:23: note: expected ‘gchar *’ but argument is of type ‘const gchar *’
 gchar*                g_strchug        (gchar        *string);
                       ^
[ 63%] Building C object src/autovalaLib/CMakeFiles/AutoVala.dir/findVala.c.o
[ 65%] Building C object src/autovalaLib/CMakeFiles/AutoVala.dir/genVapis.c.o
In file included from /usr/include/glib-2.0/glib.h:79:0,
                 from /home/stephen/autovala/install/src/autovalaLib/genVapis.c:22:
/home/stephen/autovala/install/src/autovalaLib/genVapis.c: In function ‘string_strip’:
/home/stephen/autovala/install/src/autovalaLib/genVapis.c:1215:14: warning: passing argument 1 of ‘g_strchug’ discards ‘const’ qualifier from pointer target type
  g_strstrip (_tmp1_);
              ^
/usr/include/glib-2.0/glib/gstrfuncs.h:180:53: note: in definition of macro ‘g_strstrip’
 #define g_strstrip( string ) g_strchomp (g_strchug (string))
                                                     ^
/usr/include/glib-2.0/glib/gstrfuncs.h:175:23: note: expected ‘gchar *’ but argument is of type ‘const gchar *’
 gchar*                g_strchug        (gchar        *string);
                       ^
[ 67%] Building C object src/autovalaLib/CMakeFiles/AutoVala.dir/globals.c.o
[ 69%] Building C object src/autovalaLib/CMakeFiles/AutoVala.dir/packages.c.o
/home/stephen/autovala/install/src/autovalaLib/packages.c:30:31: fatal error: readline/readline.h: No such file or directory
 #include <readline/readline.h>
                               ^
compilation terminated.
src/autovalaLib/CMakeFiles/AutoVala.dir/build.make:829: recipe for target 'src/autovalaLib/CMakeFiles/AutoVala.dir/packages.c.o' failed
make[2]: *** [src/autovalaLib/CMakeFiles/AutoVala.dir/packages.c.o] Error 1
CMakeFiles/Makefile2:202: recipe for target 'src/autovalaLib/CMakeFiles/AutoVala.dir/all' failed
make[1]: *** [src/autovalaLib/CMakeFiles/AutoVala.dir/all] Error 2
Makefile:123: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by rastersoft** [comment]
You must install the development package for READLINE (in ubuntu: libreadline-dev)

**Comment by ztefn** [comment]
Thanks, installing that package worked. But isn't that something that should be checked by cmake though?

**Comment by rastersoft** [comment]
Yes, in theory it should be checked by cmake; unfortunately, it seems that cmake can check only libraries that have a pkg-config file, and readline hasn't it :(
