### ISSUE TITLE
Enable recognition of c header files

### ISSUE THREAD

**Issue by andrewbenton** [rastersoft/autovala#45]
I ran into the issue of trying to package libgee under cmake where autovala doesn't pull over c header files, though they can be listed in a .vapi file.  I checked out the wiki, but couldn't find any support for this.

**Comment by rastersoft** [comment]
Mmmm... Why do you need to pack a library so basic like libgee?

Anyway, have you tried to pass a -Ipath_to_the_h_files command with a compile_c_options command?

**Comment by andrewbenton** [comment]
I have tried passing the "-I<path>" flag, but that hasn't helped, at least not with a relative path, and I don't want to add an absolute path to a redistributable package.  The reason that I'm packaging libgee under cmake is to use it for a class where the professor might not have it.

That aside, I think that being able to include .h files is necessary in the case where any library under autovala wants to use more customized c functionality like macros, which is what libgee is doing.

**Comment by rastersoft** [comment]
Remember that the path must be relative to the current binary being created...

**Comment by andrewbenton** [comment]
Perhaps I'm doing something wrong, but I have the headers at both src and src/vapis and I have 'compile_c_options: -Isrc -Isrc/vapis -Ivapis -I.'.  The binary is being created as src/libgee.

**Comment by rastersoft** [comment]
You must put "-lvapis", because the GCC instance is launched in the same path than the source root.

**Comment by rastersoft** [comment]
Ok, it seems it is not as easy as I believed... This weekend I'll try to implement it.

**Comment by rastersoft** [comment]
Ok, I uploaded a version to trunk that should allow to do this: just add to the .avprj file, in your binary section, an statement with "h_folder: PATH", with PATH the path to the folder where the .h files are (relative to the binary folder itself). You can add as many h_folder statements as you need.

Please, check it and comment me if it works.

**Comment by rastersoft** [comment]
When you confirm that this patch works, I will add autodetection of the folders with .h files.

**Comment by andrewbenton** [comment]
Adding the "h_folder: PATH" does the trick.  Thanks for the update!

**Comment by rastersoft** [comment]
Ok, now it should autodetect the folders with .h files.
