### ISSUE TITLE
Parallel valac / gcc defines

### ISSUE THREAD

**Issue by andrewbenton** [rastersoft/autovala#46]
I'm unsure of how difficult this would be, but it might be advantageous to carry cmake defines into both vala and C, so that it you have a "define: DEBUG" statement, and it is set to true in the CMake, then it flags as true for the vala and c source.

**Comment by rastersoft** [comment]
Currently, if you put some kind o #if in vala source code, you can also set them in CMake.

**Comment by andrewbenton** [comment]
Not quite.  I submitted a pull request that shows it a bit more clearly.  Currently, if a project mixes C headers and source files in, but wanted to use something like '#ifdef DEBUG', you have to append that to the CMAKE_C_FLAGS, set it manually in the source, or you're SOL.  It makes sense (to me anyway :))that if you have an '#if DEBUG' in vala, and an '#ifdef DEBUG' in C, then they should both be activated by the CMake define.

**Comment by rastersoft** [comment]
Added. Thanks!
