### ISSUE TITLE
POT file creation fails when using non-ASCII text while running "autovala po"

### ISSUE THREAD

**Issue by ztefn** [rastersoft/autovala#48]
Recently I added unicode characters to some translatable strings (to feature nicer quotation characters, ellipses, etc).

I just noticed this apparently is causing POT file creation to fail, because by default the input files are assumed to be in ASCII:

<pre>
Launching command xgettext -d appname -o appname.pot -p po --keyword='_' -f po/POTFILES.in
Warning: Failed to run 'xgettext' to generate the base POT file

Command output: 
Error output: xgettext: Non-ASCII string at (null):0.
          Please specify the source encoding through --from-code.
</pre>

I've worked around the issue by manually running said xgettext command with the option "--from-code=UTF-8" added. This seemed to work. I suppose it would be usefull for autovala to always add this option, or be able to specify po(t) encoding in the avprj file.

**Comment by rastersoft** [comment]
Yes... in theory. In practice, it is recommended to use only ASCII (which means english) in the source code, and translate to other languages with the gettext library. In fact, I remember some years ago that I created a program with the texts in spanish and used gettext to add other languages, but it didn't work. The library had problems. Maybe it has been fixed, but...

**Comment by ztefn** [comment]
Since a few years, GNOME has switched to Unicode for certain characters:
https://developer.gnome.org/hig/stable/typography.html.en#unicode
http://worldofgnome.org/gnome-to-use-the-unicode-ellipsis-instead-of-three-periods/

**Comment by bb010g** [comment]
UTF-8 is the de facto standard for Linux as far as I've seen. Assuming ASCII makes things really messy for international users.

**Comment by rastersoft** [comment]
Ok, you win :)
