### ISSUE TITLE
gedit plugin isn't in gedit

### ISSUE THREAD

**Issue by bb010g** [rastersoft/autovala#52]
I installed the gedit_plugin (which I would recommend renaming to autovala_gedit_plugin) through pacman, but it's not showing up in gedit. Arch 64 bit.

**Comment by rastersoft** [comment]
Currently the Gedit plugin for autovala isn't being packaged, nor in pacman, neither in rpm or deb, due to lack of time. I don't know what did you install :?

**Comment by bb010g** [comment]
You have a PKGBUILD sitting in the gedit_plugin folder...

**Comment by rastersoft** [comment]
It is now available in my homepage as a separate package.
