### ISSUE TITLE
cannot find gee.h when compiling

### ISSUE THREAD

**Issue by eumario** [rastersoft/autovala#53]
I just recently added in gee to be used in my vala program, and for some reason, when I attempt to use autovala to setup my CMakeLists.txt file, it fails to find #include <gee.h>, and I see from the output of the Makefile, that there is no -I/usr/include/gee-0.8.  I am running ElementaryOS Freya, with Vala 0.28, libgee-0.8 installed, with vapi available for gee, and the gee-0.8.pc available as well.

Any help would be much appreciated.

**Comment by rastersoft** [comment]
Did you run "autovala update", and then run again "cmake .." from an empty install folder? (It is important to have it empty, because cmake do odd things when modifying CMakeList.txt files and running it in an already filled folder)

**Comment by eumario** [comment]
This fixed the issue, as mentioned in the other bug.  Thank you.
