### ISSUE TITLE
Autovala does not ignore src/Config.vala when updating

### ISSUE THREAD

**Issue by eumario** [rastersoft/autovala#54]
src/Config.vala is a generated file by the CMake system, but whenever attempting to add an ignore statement to the project file, says: Warning: Trying to add twice the path Config.vala, and it removes the ignore, and adds the vala_source: Config.vala to the project.  This causes issues, as you are forced into another step to remove the Config.vala file from the src folder, before issuing the autovala update command.  This behavior needs to be fixed, as it should not be adding Config.vala at all, with it being a generated file.

**Comment by rastersoft** [comment]
src/Config.vala should not exist, only src/Config.vala.cmake. That file is transformed into install_folder/src/Config.vala when you run "cmake ..".

Are you maybe running "cmake .." from src/?

**Comment by eumario** [comment]
That was my fault, I was compiling from the wrong area.  When I first tried to use autovala with cmake, I tried to do a build directory, and it wasn't working.  But now it's working, and the Config.vala is no longer being detected.
