### ISSUE TITLE
failure with multiple packages in using

### ISSUE THREAD

**Issue by zabbal** [rastersoft/autovala#58]
The following code:

using Gtk, Notify;

results in following warning:

Warning: Can't resolve Using Gtk, Notify

The result fails to compile. Replacing it with
using Gtk;
using Notify;
serves as workaround fixing compilation but that's kinda ugly - autovala should not impose additional restrictions on the sources.

**Comment by rastersoft** [comment]
Ooooops!!!! Never considered that syntax. I'll fix it.

**Comment by rastersoft** [comment]
Ok, fixed.
