### ISSUE TITLE
Add support for AppData XML files

### ISSUE THREAD

**Issue by ztefn** [rastersoft/autovala#59]
AppData xml files provide application metadata (just like desktop files, but more elaborate) and are installed as /usr/share/appdata/%{id}.appdata.xml

It's currently foremost used by GNOME Software Center. The AppData specification can be found here: http://people.freedesktop.org/~hughsient/appdata/

**Comment by rastersoft** [comment]
Interesting... will read it.

**Comment by rastersoft** [comment]
Hi again:

It is a very good idea! In fact, I can use that data, when available, to generate package specific data like descriptions and so on.

But I have a little doubt: how are translations stored? I read the whole specification, and checked the ITS documentation too, but I'm not sure where translated strings are stored. Are they stored in a new XML file with the language specified in the filename? All the translated strings are stored in the same XML, using an attribute to specify the language of that element (like in .desktop files)? It is not clear... (at least for me)

**Comment by rastersoft** [comment]
Forget it, I just checked a file and found everything is in the same XML file.

**Comment by ztefn** [comment]
Yes, the translations seems to be stored in the XML file itself, by using xml:lang attibutes on nodes, like summary, description, p(aragraphs) and even screenshots. For example: https://fedoraproject.org/wiki/Packaging:AppData#.appdata.xml_file_creation

Additionally to dynamically generate a translated XML it appears intltool can be used, by creating an *.appdata.xml.in file and using _underscores for translatable nodes:
https://wiki.gnome.org/Initiatives/GnomeGoals/AppDataGnomeSoftware#line-70
https://github.com/hughsie/appstream-glib/blob/master/data/tests/intltool.appdata.xml.in

**Comment by rastersoft** [comment]
Ok, done. And also uploaded the binary packages in my homepage.

**Comment by ztefn** [comment]
Wow, that's fast! And it works like a charm: http://bazaar.launchpad.net/~ztefn/haguichi/1.3/revision/41

Thanks again!

**Comment by rastersoft** [comment]
Now it should be fine. Please, check it.

El 07/11/15 a las 21:49, Stephen Brandt escribió:
>
> AppData xml files provide application metadata (just like desktop
> files, but more elaborate) and are installed as
> /usr/share/appdata/%{id}.appdata.xml
>
> It's currently foremost used by GNOME Software Center. The AppData
> specification can be found here:
> http://people.freedesktop.org/~hughsient/appdata/
> <http://people.freedesktop.org/%7Ehughsient/appdata/>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rastersoft/autovala/issues/59>.
>


-- 
Nos leemos
		             RASTER      (Linux user #228804)
sergio.costas@rastersoft.com        http://www.rastersoft.com
