### ISSUE TITLE
Strange issue with scratch plugin

### ISSUE THREAD

**Issue by xdave** [rastersoft/autovala#60]
When attempting to create a project or add a target to a project within Scratch, when typing a name for the project or target, the OK button is grayed out, and I get these errors in the terminal from Scratch:

`[WARNING 00:35:01.795989] [Gtk] Could not find signal handler 'autovala_plugin_create_new_project_folder_changed'.  Did you compile with -rdynamic?
[WARNING 00:35:01.796034] [Gtk] Could not find signal handler 'autovala_plugin_create_new_project_folder_changed'.  Did you compile with -rdynamic?
[WARNING 00:35:01.796068] [Gtk] Could not find signal handler 'autovala_plugin_create_new_project_name_changed'.  Did you compile with -rdynamic?`

I tried adding the `gmodule-2.0` package and `-Wl,--export-dynamic -rdynamic` to the linker flags (says google) to everything down the chain (from autovala to scratch) with no effect.

If it helps, I'm on Arch Linux.

BTW, awsome build system. :)

**Comment by rastersoft** [comment]
You are right: there is a problem with GtkBuilder connect_signals call. I fixed it and uploaded new packages to my homepage.

Thanks!
