### ISSUE TITLE
Another strange issue (with gedit plugin :)

### ISSUE THREAD

**Issue by xdave** [rastersoft/autovala#61]
Hi again!  So, it seems a regression of issue #52 has come up again.  The plugin does not show up in the plugin preferences (v 3.18.2, arch linux).

However, if you cannot reproduce this, it's probably because my install is messed up.  Lately I cannot get the `gedit-code-assistance` plugin to do anything (at least for `Vala`) in gedit.  I should probably try on another machine..... Let me know if you have any insight.

Thanks again for a truly impressive piece of software :)

**Comment by rastersoft** [comment]
In my system works fine. Check that you removed all the files in /usr/local:

    /usr/local/lib/scratch/plugins/autovala/autovalascratch.plugin
    /usr/local/lib/scratch/plugins/autovala/autovalascratch.so

**Comment by rastersoft** [comment]
How did you install the old autovala and the new one? You should install both with the same method (or you compile it from git repo, or use the package for arch).

In case you compiled it, you can delete it by deleting the following files:

    /usr/local/bin/autovala
    /usr/local/lib/libAutoVala*

and then, run

    sudo ldconfig

**Comment by xdave** [comment]
- I install autovala using the PKGBUILD included in the source.
- I installed the gedit_plugin using the PKGBUILD included in it's source tree.
- I installed the scratch plugin like this:
```
cd scratch_plugin/
mkdir install
cd install
cmake .. -DCMAKE_INSTALL_PREFIX=/usr
make
sudo make install
```

The problem I'm having is with the gedit plugin.

**Comment by rastersoft** [comment]
Oh, ok: ensure that the GEdit files have been installed at /usr, and not at /usr/local, please.

**Comment by xdave** [comment]
```> $ cat ~/src/autovala/gedit_plugin/install/install_manifest.txt
/usr/share/gedit/plugins/autovala/libautovalagedit.so.1.0.0
/usr/share/gedit/plugins/autovala/libautovalagedit.so.1
/usr/share/gedit/plugins/autovala/libautovalagedit.so
/usr/share/gedit/plugins/autovala/autovalagedit.h
/usr/share/gedit/plugins/autovala/autovalagedit.vapi
/usr/share/gedit/plugins/autovala/autovalagedit.deps
/usr/share/gedit/plugins/autovala/autovalagedit-1.0.gir
/usr/share/gedit/plugins/autovala/autovalagedit.pc
/usr/share/locale/es/LC_MESSAGES/gedit_plugin.mo
/usr/share/gedit/plugins/autovala/autovala.plugin```

**Comment by xdave** [comment]
I have the default `gedit` that comes with Arch Linux.  Not a custom build.

**Comment by xdave** [comment]
I think I found the problem.  Here's the contents of /usr/share/gedit/plugins/autovala/autovala.plugin:

```[Plugin]
Module=autovalagedit.so
IAge=3
Name=Autovala Plugin
Description=An AutoVala Plugin for Gedit
Authors=Sergio Costas <raster@rastersoft.com>
```

It's pointing to a file called `autovalagedit.so`, which doesn't exist.  The file is called `libaudiovalagedit.so`...

**Comment by rastersoft** [comment]
No, I found the problem: the gedit team changed the path where to store the plugins. Now it is /usr/lib/gedit/plugins.

I'll update the project, give me a minute.

**Comment by rastersoft** [comment]
Ok, it's not as easy as I think: in Fedora it must go to /usr/lib64, but in debian must go to /usr/lib... I suspect I must do some changes in Autovala to be able to support this...

**Comment by rastersoft** [comment]
Until then, install the plugin locally, by downloading the code from the git repo

**Comment by xdave** [comment]
Well I got it to work.

I just moved `autovala.plugin` and `libautovala.so*` to /usr/lib/gedit/plugins.

I also had to edit `autovala.plugin` and remove the `.so` part of the `Module` entry.

**Comment by efernandesng** [comment]
I make a PR #62 to solve this issue. It replaces /**share**/.. by /**lib**/... in **data** and **src** `CMakeList.txt` files.

`sed -i 's/share/lib/g' ./{data,src}/CMakeLists.txt`

[PKGBUILD](https://gist.github.com/efernandesng/208e11c247d6588afee3#file-pkgbuild)

**Comment by rastersoft** [comment]
I'm working on a more generic fix. Give me a little more time, please.

**Comment by efernandesng** [comment]
@rastersoft ok, thanks! I'll close PR

**Comment by rastersoft** [comment]
Ok, it should work fine now.

**Comment by rastersoft** [comment]
Fixed and uploaded packages.
