### ISSUE TITLE
How to set debugging?

### ISSUE THREAD

**Issue by astronouth7303** [rastersoft/autovala#63]
Is there a canonical way to compile for debugging? Things like including debugging symbols and that vala passes along the correct line numbers and file names.

**Comment by rastersoft** [comment]
To do it, currently you must edit the .avprj file and add

compile_options: -g

in each binary/library in which you want to add debugging symbols. If you want to do it conditional, you can do:

if DEBUG
compile_options: -g
end

Then, using "cmake .. -DDEBUG=on" will enable the debug.

**Comment by astronouth7303** [comment]
Hmm... autovala doesn't seem to like [my avprj file](https://github.com/astronouth7303/gi3-edit/blob/8b963d9376473e674e6df299644d74ededd1baf4/gi3-edit.avprj) anymore:

```
$ autovala update
Updating project file
Error: Invalid command compile_options after command define (line 7)
Aborting
```

**Comment by astronouth7303** [comment]
Oh, the `compile_options` line has to be after a `vala_binary` line, I see now.
