### ISSUE TITLE
Unable to install: bzr: ERROR: Not a branch

### ISSUE THREAD

**Issue by darkoverlordofdata** [rastersoft/autovala#64]
I'm trying to install, and the first step:

bzr checkout lp:~elementary-apps/+junk/cmake-modules

fails with 

bzr: ERROR: Not a branch: "bzr+ssh://bazaar.launchpad.net/~elementary-apps/+junk/cmake-modules/".

**Comment by rastersoft** [comment]
Sorry, but I'm not sure that this message comes here... Autovala doesn't use bazaar.

**Comment by darkoverlordofdata** [comment]
It's the first instruction in INSTALL.md:
# HOW TO INSTALL

You need CMake, Vala 0.20 or later, libgee and gtk+.
The repository includes a version of CMake for Vala
that includes some changes (not mine) to support
Valadoc. These changes still aren't available at the
oficial repository. You can get the oficial files with

    bzr checkout lp:~elementary-apps/+junk/cmake-modules

This will create a folder called *cmake-modules*. Inside
it will be a folder called *cmake*. Copy the later to the
Autovala project folder, overwriting the files inside.

Don't forget to keep the files FindValadoc.cmake and
Valadoc.cmake, needed to work with Valadoc.

To compile and install it, just open a terminal, go
to the directory where you downloaded the git repository
and type:

    mkdir install
    cd install
    cmake ..
    make
    sudo make install
    sudo ldconfig

If you are using GTK 3.4 or previous, you must specify it
to avoid the plugins to use newer widgets, not supported
in old GTK versions:

    mkdir install
    cd install
    cmake .. -DGTK_OLD=on
    make
    sudo make install
    sudo ldconfig

Also, if you are using ElementaryOS Luna, the pandoc version
available is also too old, so you must install the one from
ubuntu 14.04 at least. The packages needed are pandoc,
pandoc-data and libicu52, which can be downloaded from

    http://packages.ubuntu.com

The Gedit and Scratch plugins are compiled and installed
separately. Just follow the instructions available in each
folder.

**Comment by rastersoft** [comment]
You only need that if you want the original files. They aren't needed to use autovala.

**Comment by darkoverlordofdata** [comment]
Thanks. I could instll valadoc. But you still refer to this module in your install, even though it does not exist: I guess I'm SOL if I want to use ValaDoc...

Remember that you need CMake, Vala 0.20 or later, libgee and gtk+. The repository includes a version of CMake for Vala that includes some changes (not mine) to support Valadoc. These changes still aren't available at the oficial repository. If you want, you can get the oficial files with:

bzr checkout lp:~elementary-apps/+junk/cmake-modules

**Comment by rastersoft** [comment]
You don't need that, the code you need is already in Autovala. I put that repository only to explain where I obtained the changes to use Valadoc with CMake. It seems the authors deleted it...
