### ISSUE TITLE
Add gresources support

### ISSUE THREAD

**Issue by astronouth7303** [rastersoft/autovala#67]
The [gresource system](https://developer.gnome.org/gio/stable/GResource.html) (and `glib-compile-resources`) is a handy way of dealing with resources, including embedding them into your program.

When there's a `.gresource.xml` file is found, `glib-compile-resources` should be called and the resulting C/H files included in the compilation, and a basic VAPI generated for it.

**Comment by rastersoft** [comment]
Mmmm... had no idea... I'll check this.

**Comment by astronouth7303** [comment]
For the record, a simple project I'm working on uses [this vapi](https://github.com/astronouth7303/gltutorial-vala/blob/master/resource.vapi) for the generated c/h files.

**Comment by rastersoft** [comment]
Thanks... Unfortunately, at this moment I have very little spare time. I've been checking it and I think it must be added to autovala. Hope to have some time during this week.

**Comment by astronouth7303** [comment]
ok! I'm really looking forward to seeing this.

**Comment by rastersoft** [comment]
A question, since you have expertise with gresources: should I create a folder, and everything inside it (even in subfolders) be considered "a gresource" to be automagically added by autovala? Maybe "data/gresources"? Or should never add files as gresources unless the user manually marks them as a gresource?

**Comment by astronouth7303** [comment]
Well, you're looking for file pattern `*.gresource.xml`. Inside it is all the files that go into that resource. The c file needs to be regenerated every time any of the files it bundles changes. The header file only needs to be generated once.

The header to go with the above VAPI only contains (of note):
```c
extern GResource *shaders_get_resource (void);
```

Seeing as it's generated from `shaders.gresource.xml`, the file name becomes the glib prefix (see below), and in my opinion should be the namespace in the VAPI as well (as is conventional in C->Vala naming). (This prefix can bet changed by passing `--c-name` to [`glib-compile-resources`](https://developer.gnome.org/gio/unstable/glib-compile-resources.html). In that project I don't use one.)

It looks like the default C name [is generated](https://github.com/GNOME/glib/blob/8c9be18bd3dff42a2352c2dac6b8f17b243d2980/gio/glib-compile-resources.c#L736-759) like this: Take the basename (before the first '.'), Replace '-' with '_', and strip out anything else that's not alphanumeric or '_' (no leading digits).

I feel like a good default behavior is to search an appropriate location (`data/resources` perhaps?) recursively for any `*.gresource.xml`, compile it in, and mangle appropriately produce a VAPI with namespaces.

Keep in mind that I think the path names inside of a .gresource.xml is relative to it, but the prefix is specificied in the gresource file. That is, don't worry about where the gresource is located for any naming or codegen, just its name and contents.

Of course, I'm not saying that there shouldn't be any overrides available. But the major reason I use autovala is that it does the right thing with no specification more than "Here's the packages I need" and "please include debugging information."

**Comment by astronouth7303** [comment]
Wow, that was a long-winded way of saying "autodetect and do the thing".

**Comment by rastersoft** [comment]
So you say to let the user create the .gresource.xml file, so autovala doesn't need to presume things about files...

I was talking about letting autovala to create the .gresource.xml, by assuming that the files in a certain folder tree are resources, freeing the programmer of that task.

**Comment by astronouth7303** [comment]
As far as I can tell, there's enough things the user has to specify (prefix, processors, compression, etc) and the file is low on boilerplate (except for the fact it's XML), that having extra specification would just be a level of indirection with no benefit.

If there was an autogeneration facility, I would make it explicit, with Vala name, project directory, and resource prefix. Except for the fact that I'm not sure what kind of heuristic would be good to use to determine if `to-pixdata` should be used. (`xml-stripblanks` is right out.) I would just turn compression on for everything that isn't being stored as a compressed type (eg, any images that don't have `to-pixdata`).

**Comment by rastersoft** [comment]
Mmmm... you are right. It is better to do it that way.

**Comment by astronouth7303** [comment]
Hm. VAPI generation may not be necessary on most platforms, but should still be included.

gio has several global functions ([`resources_lookup_data()`](http://valadoc.org/#!api=gio-2.0/GLib.resources_lookup_data), [`resources_open_stream()`](http://valadoc.org/#!api=gio-2.0/GLib.resources_open_stream)) to access resources. And on supported platforms ([GCC, MSVC, and maybe Sun Workshop?](https://github.com/ImageMagick/glib/blob/master/glib/gconstructor.h)), the resource is automatically registered into the global resource lookup.

On other platforms (eg, CLANG), [`resources_register()`](http://valadoc.org/gio-2.0/GLib.resources_register.html) has to be called with the resource (as returned by the generated code) before the global functions can be used.

**Comment by rastersoft** [comment]
Hi!

I added GResource support. It is in a branch called "gresource". Can you test it before mergin it in Master?

**Comment by rastersoft** [comment]
In the HTML documentation (and man pages) you have how to use it, and also in the TRICKS page you have an example.

**Comment by astronouth7303** [comment]
Are the resource identifiers their own namespace?

If so, you should strip the ".gresource.xml" before generating the identifier.

Also, it should probably be mentioned that this is essential for [composite templates](https://blogs.gnome.org/tvb/2013/05/29/composite-templates-lands-in-vala/).

**Comment by astronouth7303** [comment]
[Adapting an existing project](https://github.com/astronouth7303/gltutorial-vala/tree/autovala), I got the attached errors.

[CMakeOutput.txt](https://github.com/rastersoft/autovala/files/278180/CMakeOutput.txt)

**Comment by rastersoft** [comment]
Mmmmm... I presume you put the .gresource.xml file in the project's root. Can you move it into 'data' and test again?

**Comment by rastersoft** [comment]
BTW: the identifier in the .avprj file is used only internally by AutoVala. It doesn't leak to the source code.

**Comment by rastersoft** [comment]
Confirmed: autovala doesn't support files located in the project's root O:)

I'll try to fix it. Meanwhile, please, try to move the .gresource.xml file into 'data', please.

**Comment by rastersoft** [comment]
Ok, fixing the problem of having project files in the root is quite complex to fix. Anyway, it is recommended to always put files inside folders, to keep the root as clean as possible, so I just added an advertisement if a file in the root folder is detected.

**Comment by astronouth7303** [comment]
Yeah, I just had everything in root because it was a tiny project with a hand-crafted makefile. I'll shuffle things around and get back to you.

**Comment by rastersoft** [comment]
Remember that "autovala init" greatly simplifies everything ;)

**Comment by rastersoft** [comment]
So...?

**Comment by rastersoft** [comment]
Done.
