### ISSUE TITLE
Custom config file support

### ISSUE THREAD

**Issue by meghprkh** [rastersoft/autovala#68]
How can I have a custom config file? Currently if I edit the file it is rewritten on `update`.

I want this as I dont want to have another namespace in my library but just a private constants static singleton.

I think a simple way would be to process all cmake files and add them to the cmakelists and generate the default file on `init`

**Comment by rastersoft** [comment]
As I explain in the documentation, lines without an asterisk are considered "manual ones", so they won't be deleted after update.

**Comment by meghprkh** [comment]
Sorry if I am asking this like in a help forum but I meant using a custom
Config.cmake file instead of the default one and I donot want to include
the default one (it is overwritten everytike I do autovala update)

Regards,
Megh Parikh

**Comment by rastersoft** [comment]
Ok, now I understand.

You should write your CMAKE file with a name different than CMakeLists.txt, and then use the `include` statement in the .avprj file to add your file to the base one created by autovala. Also you can use the `ignore` statement in the .avprj file to avoid autovala processing some files.
