### ISSUE TITLE
Gresources: UI resource not found

### ISSUE THREAD

**Issue by DevNIX** [rastersoft/autovala#73]
Hi again! :D 

I'm trying to code again a project in Vala after a long while, and I'm starting it with Autovala as usual. Looking at existing projects, I've just discovered the GResource featureand the annotation syntax, which I find amazing but barely documented :(

Right now, I've successfully created a GResource file, a glade .ui file, and included it in Autovala project's file, but it seems like it's not being included con my binary.

The compiler throws the following error:
```
/home/devnix/development/Dev_NIX/TempestadesTracker/src/TempestadesTracker/MainWindow.vala:4.3-4.42: error: UI resource not found: `/io/devnix/tempestadestracker/interface/MainWindow.ui'. Please make sure to specify the proper GResources xml files with --gresources.
  class MainWindow : Gtk.ApplicationWindow {
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Compilation failed: 1 error(s), 1 warning(s)
```

I just don't get it, because I'm adding the `use_gresource` line to my binary. 

```
### AutoVala Project ###
autovala_version: 21
project_name: TempestadesTracker
vala_version: 0.30

*gresource: tempestadestracker_gresource_xml data/tempestadestracker.gresource.xml


vala_binary: src/tempestadestracker
compile_options: --target-glib=2.38 -g
use_gresource: tempestadestracker_gresource_xml
*vala_check_package: atk
*vala_check_package: cairo
*vala_check_package: gdk-3.0
*vala_check_package: gdk-pixbuf-2.0
*vala_check_package: gio-2.0
*vala_check_package: glib-2.0
*vala_check_package: gobject-2.0
*vala_check_package: gtk+-3.0
*vala_check_package: pango
*vala_check_package: x11
*vala_source: TempestadesTracker/MainWindow.vala
*vala_source: main.vala

*po: po

*translate: vala src/TempestadesTracker/MainWindow.vala
*translate: vala src/main.vala
*translate: glade data/interface/MainWindow.ui

*data: data/local

*doc: doc
```

For more info, this is my GResource file
```xml
<?xml version="1.0" encoding="UTF-8"?>
<gresources>
  <gresource prefix="/io/devnix/tempestadestracker">
    <file compressed="true" preprocess="xml-stripblanks">interface/MainWindow.ui</file>
  </gresource>
</gresources>
```

And the vala file where I try to load the resourcec
```vala
namespace TempestadesTracker {

  [GtkTemplate (ui = "/io/devnix/tempestadestracker/interface/MainWindow.ui")]
  class MainWindow : Gtk.ApplicationWindow {

  }

}
```

What I could be missing? This could be a bug? Or maybe this isn't an Autovala bug?

I can attach a zip with the project if you need it (it's very simple)

**Comment by rastersoft** [comment]
Try to delete all the content inside the "install" folder, run "autovala update", and the "cmake ..", to ensure that everything has been made right.

**Comment by DevNIX** [comment]
Yup, did it quite a lot of times while experimenting :(

**Comment by rastersoft** [comment]
Ok, it seems that the .c file with the resources must be passed directly to valac. I'll try to fix it tomorrow.

**Comment by rastersoft** [comment]
Until then, try to add this line to the binary part in the .avprj file:

compile_options: --gresources /full/path/to/the/gresources/xml/file

**Comment by rastersoft** [comment]
Ah, y veo que eres de Zaragoza :)

**Comment by DevNIX** [comment]
Chí, nos carteamos hace un par de años cuando te pedía ayuda para iniciarme con Vala y tu Autovala, que me parece una herramienta BRUTAL.

Espero acabar un proyecto básico este año y realizar más cosas con este lenguaje, si no cae en un abandono mayor su desarrollo... :(

**Comment by DevNIX** [comment]
Okey, I've already tried once the compile_options fix but I think the route might be wrong, I will try it again as a temporary fix. Thank you!

**Comment by rastersoft** [comment]
Just uploaded a new version of Autovala that fixes this. Please, try it. You can choose between downloading it from the git repository, or install from packages downloaded from my home page.

**Comment by rastersoft** [comment]
Por lo que estoy viendo en la lista, parece que hay gente que quiere colaborar en el compilador, así que creo que tendremos suerte y seguirá adelante.

**Comment by DevNIX** [comment]
It seems like it compiles now! The next step for me is to figure out how to create this templates with Glade, and start working on. Thank you so much! :D

**Comment by my-tien** [comment]
Hello,
17 days later I have exactly the same file structure as DevNIX but his .avprj throws errors for me. I am using vala version 0.32.

The thing is, adding `use_gresource: ` or `use_resouce` (as in the doc) below `*vala_binary` causes: 

```
Error: Invalid command use_gresource after command vala_binary (line 9)
Aborting
```

Similarly the following line `*gresource: data_gresource_xml data/data.gresource.xml`  is accompanied with below warning:

```
** (process:2397): CRITICAL **: auto_vala_element_base_configureLine: assertion 'self != NULL' failed
```

If I let autovala do the setup, it simply adds this to my .avprj:

```
*glade: data/interface/application_window.ui
```

If I then add  `compile_options: --target-glib=2.38 -g` to fix the glib version problem, I end up with:

```
/path/to/my/repo/src/main.vala:6.1-6.27: error: UI resource not found: `/org/interface/application_window.ui'. Please make sure to specify the proper GResources xml files with --gresources.
public class MyWidget : Box {
^^^^^^^^^^^^^^^^^^^^^^^^^^^
Compilation failed: 1 error(s), 0 warning(s)
```

**Comment by rastersoft** [comment]
Did you wrote a message about nine hours ago? I received it in my mail, but there is no new entries here... You talk about receiving an error when using the gresources...

**Comment by rastersoft** [comment]
Ops... no, it wasn't you, it was someone called my-tien... :?

**Comment by my-tien** [comment]
Yes, it was me. I had problems with this too but then I noticed an error on my part, so the message became obsolete.

**Comment by rastersoft** [comment]
Oh, ok. Sorry then O:)
