### ISSUE TITLE
```error: glib 2.38 is required``` on ```make```

### ISSUE THREAD

**Issue by x421** [rastersoft/autovala#74]
Hi,

just getting started with autovala and I ran into the following problem:
```
/home/karl/Projekte/character_sheets/src/UI/Welcome.vala:4.5-4.15: error: glib 2.38 is required for using Gtk templates (with --target-glib=2.38)
```
The generated project file looks fine to me, what could cause the problem?
```
### AutoVala Project ###
autovala_version: 24
project_name: character_sheets
*vala_version: 0.34

*vala_binary: src/character_sheets
*vala_check_package: atk
*vala_check_package: cairo
*vala_check_package: gdk-3.0
*vala_check_package: gdk-pixbuf-2.0
*vala_check_package: gio-2.0
*vala_check_package: glib-2.0
*vala_check_package: gobject-2.0
*vala_check_package: gtk+-3.0
*vala_check_package: pango
*vala_check_package: x11
*vala_source: UI/Headerbar.vala
*vala_source: UI/MainWindow.vala
*vala_source: UI/Welcome.vala
*vala_source: character_sheets.vala


*po: po

*translate: glade data/interface/welcome.ui
*translate: vala src/UI/Headerbar.vala
*translate: vala src/UI/MainWindow.vala
*translate: vala src/UI/Welcome.vala
*translate: vala src/character_sheets.vala

*data: data/local

*doc: doc

*glade: data/interface/welcome.ui
```

**Comment by rastersoft** [comment]
By default, your valac version compiles with compatibility with old glib versions, so you need to pass the parameter "--target-glib 2.38" to the vala compiler. To do so in Autovala, just append this line inmediately after the "*vala_binary: src/character_sheets":

compile_options: --target-glib 2.38

**Comment by rastersoft** [comment]
And, of course, if you are creating several binaries and/or libraries in a single autovala project, you have to add that in each binary/library section.

**Comment by x421** [comment]
Thank you, that fixed the issue.

Elementary OS 0.4 Loki by the way.
