### ISSUE TITLE
refresh adds bogus libraries

### ISSUE THREAD

**Issue by darkoverlordofdata** [rastersoft/autovala#81]
How can I tell autovala to skip a library? The refresh command sometimes picks up bogus libraries. I have 2 different scenarios:

I am only using sdl2 in my code. I have both sdl and sdl2 installed on my system. Autovala adds both:
*vala_check_package: sdl 
*vala_check_package: sdl2

I choose namespace sdx for some of my code. But there is an installed library - libSdx.so on my system, so autovala adds 
*vala_check_package: sdx

It also includes the dependencies of the bogus libraries, so I have to clean up the avprj file manually everytime I refresh a project.

**Comment by rastersoft** [comment]
For the first case, remove the "*vala_check_package: sdl", and remove the asterisk from the sdl2 line. That should fix it.

About the second case, the solution is obvious: use other namespace.

**Comment by darkoverlordofdata** [comment]
I meant to say, before I fat-finger the close button -

That works - taking out the asterisk on sdl2 prevents it from also selecting sdl.

As for the other, I agree, it's an edge case. I'm intentionally hiding a library to emulate it for emscripten.
