### ISSUE TITLE
[Feature request] symlinks during install

### ISSUE THREAD

**Issue by cromerc** [rastersoft/autovala#85]
It would be nice to have a way to make symlinks during install. I think that there are 2 possible ways that this could be implemented.
`custom: target link symlink`
Basically take advantage of the already existing custom tag but instead of copying a file create a symlink.

or just a symlink tag:
`symlink: target link`

Right now I do some ugly hacky stuff to get symlinks created during the install step, it would be nice if autovala had support for symlinks built in.

**Comment by rastersoft** [comment]
You are right, I will check the best way of doing it.

**Comment by rastersoft** [comment]
Before this, a question: in which cases are you generating links? This is: why do you need to create a link? Just in case those links should be created automagically by autovala...

**Comment by cromerc** [comment]
In this particular case only 1 link needs to be created. A link to the binary "pamac-manager" called "pamac-updater" both the binary and the symlink are in /usr/bin. This symlink when run makes pamac-manager open the updates tab in the manager program instead of the default search view tab.

**Comment by rastersoft** [comment]
Then I think it would be better to add an specific "alias" statement for binaries.

**Comment by cromerc** [comment]
That would work perfectly.

**Comment by cromerc** [comment]
I forgot, there is something that upstream pamac does with symlinks that I don't do currently. They link the systemd timer files to systemd so that it auto enables the services:
```
ln -srf $(libdir)/systemd/system/pamac-cleancache.timer $(sysconfdir)/systemd/system/multi-user.target.wants
ln -srf $(libdir)/systemd/system/pamac-mirrorlist.timer $(sysconfdir)/systemd/system/multi-user.target.wants
```

I don't do this in my fork of pamac because we are using it in a systemd free distro, but this is a use case that might come up for you in the future.

**Comment by rastersoft** [comment]
Mmm... I see...

**Comment by rastersoft** [comment]
Anyway, I have troubles finding how to do a symlink in meson... I already implemented the aliases in cmake.

**Comment by cromerc** [comment]
This might help:
https://github.com/manjaro/pamac/blob/master/src/meson.build#L92

**Comment by rastersoft** [comment]
Ok, added support for aliases for binaries. Just add the statement "alias: NAME_FOR_BINARY_ALIAS" in the desired "vala_binary" group.

**Comment by cromerc** [comment]
Works fine for meson, but fails with cmake:
`ln: failed to create symbolic link '//usr/bin/pamac-updater': Permission denied`

**Comment by rastersoft** [comment]
What????? That makes no sense... I'll check it again.

**Comment by rastersoft** [comment]
I'm testing it and it works...

**Comment by rastersoft** [comment]
Could you fully delete the content of the "install" folder and run again "cmake .." inside it to ensure that there are no residues? Sometimes cmake fails if a previous precompilation has failed...

**Comment by cromerc** [comment]
I will double check when I get home, but I am building it in the PKGBUILD generated by autovala which has the rm -rf install line in it, should not have any previous build in it but I will take a look.

**Comment by cromerc** [comment]
Nope, not a build folder problem, still failing after I manually deleted it. Here is what I have in PKGBUILD:
```
build() {
	rm -rf ${startdir}/build
	mkdir -p ${startdir}/build
	cd ${startdir}/build
	cmake .. -GNinja -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=/usr/lib -DCMAKE_INSTALL_SYSCONFDIR=/etc -DICON_UPDATE=OFF -DDISABLE_AUR=ON
	ninja
}

package() {
	cd ${startdir}/build
	DESTDIR="$pkgdir" ninja install
}
```

**Comment by cromerc** [comment]
Found the solution.
DESTDIR is an environment variable, to get it to process correctly under cmake it should be like this:
`install(CODE "execute_process(COMMAND ln -svf pamac-manager \$ENV{DESTDIR}/${PREFIX}/${ALIAS_DESTINATION_PATH}/pamac-updater )")`

\$ENV{DESTDIR}

By making this change it now works for me.

**Comment by rastersoft** [comment]
Ok, that makes sense. Fixing it.

Anyway, it is the first time I see using cmake+ninja :)

**Comment by rastersoft** [comment]
Done. Test it and tell me.

BTW, about the links for the systemd services, I think there should be specific statements for that in the avprj file (enable_systemd_service and disable_systemd_service).

**Comment by cromerc** [comment]
Great, now it works under both cmake and meson.

About the systemd services, I don't mind as long as it is optional. For example in arch linux it is common practice that no systemd services auto enable nor start, the user enables them manually by running systemctl service enable in the console. However Ubutnu takes a different stance, they auto enable and autostart systemd services with triggers in their packages.

I personally believe that enabling/disabling/starting/stopping services/timers is the responsibility of the person creating the package for the distro, not the choice of the software creator. The 2 distros I am a developer for (Artix Linux and Cromnix Linux) do not have systemd in their repos, naturally this means that enable systemd services would fail in these distros.

The only thing that I would like is for it to install the systemd service and timer files automatically to the correct location, but without actually enabling or starting them.

**Comment by rastersoft** [comment]
Oh, ok, so it is only in the packages itself. Then it is settled: no systemd enable or disable commands in autovala.

**Comment by cromerc** [comment]
Looks like I spoke too soon. Your change fixed cmake but broke meson:
```
ln: failed to create symbolic link '$ENV{DESTDIR}//usr/bin/pamac-updater': No such file or directory
Failed to run install script '/usr/bin/sh -c ln -sf pamac_manager \\$ENV{DESTDIR}/${MESON_INSTALL_PREFIX}/bin/pamac-updater'
FAILED: meson-install 
/usr/bin/python /usr/bin/meson --internal install /home/cromer/Desktop/projects/pamac-classic/build/meson-private/install.dat
ninja: build stopped: subcommand failed.
```

**Comment by rastersoft** [comment]
Ops!!!!! You are right!!!

**Comment by rastersoft** [comment]
Ok, NOW it should work O:)

**Comment by cromerc** [comment]
Yup, works now. Lo siento por ser tan exigente. ;)

**Comment by rastersoft** [comment]
En absoluto, te lo agradezco. No hay nada como un buen control de calidad :)
