### ISSUE TITLE
[Feature request] More automatic file detection options

### ISSUE THREAD

**Issue by cromerc** [rastersoft/autovala#87]
I would like to request some more automatic file detection options for the data directory.
This is my current custom tags:
```
custom: data/config/pamac.conf
custom: data/dbus/org.pamac.system.conf
custom: data/dbus/org.pamac.user.service
custom: data/dbus/org.pamac.system.service
custom: data/systemd/pamac-system.service
custom: data/systemd/pamac-cleancache.service
custom: data/systemd/pamac-cleancache.timer
custom: data/systemd/pamac-mirrorlist.service
custom: data/systemd/pamac-mirrorlist.timer
custom: data/polkit/org.pamac.policy
custom: data/mime/x-alpm-package.xml
```
- First of all, files in the data/config should be detected then installed into "/etc".
- I can't use the currently existing dbus file auto detection because of a flaw it has. It installs org.pamac.user.service just fine... but org.pamac.system.service is installed into the wrong directory. It should be in "/usr/share/dbus-1/system-services" however the it is being installed into "/usr/share/dbus-1/services" which is incorrect and fails to run.
- custom: data/dbus/org.pamac.system.conf is a dbus config file, it should be detected and installed to "/etc/dbus-1/system.d". My suggestion would be to have all dbus files in "data/dbus" this way the .conf files in the dbus folder would be detected and installed in the correct place.
- Systemd service and timer files should be installed in "/usr/lib/systemd/system" again a systemd directory in data should contain these files.
- org.pamac.policy is a polkit policy file, any .policy file detected in data should be installed into "/usr/share/polkit-1/actions".
- x-alpm-package.xml contains mime-type information for the project so that when a user double clicks on a file it opens it with our software. It is in an .xml file, so I believe for auto detection it would be a good idea to use the "/data/mime" directory which then needs to install the files into "/usr/share/mime/packages"

_Sent from my Moto G(4) using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by rastersoft** [comment]
Ok, so a proposal:

* add the "dbus_system_service" statement for system services, and assign there those dbus files that end in ".system.service" in the "data/dbus" folder.

* add with the "dbus_service" statement the files at "data/dbus" folder ended in ".service"

* add the "config" statement, and install the file referred there into /etc. Add with this statement all the files located at data/config

* add the "dbus_config" statement, which installs the pointed file to /etc/dbus-1/system.d. Add with this statements all the files ended in .conf in the "data/dbus" folder.

* add the "polkit" statement that installs the referred file into "share/polkit-1/actions", and add with it files at "data" and childs that end in ".policy"

* add the "mimetype" statement that installs the referred file into "share/mime/packages", and add with it files at "data/mimetypes"

**Comment by cromerc** [comment]
The proposal sounds good to me.

**Comment by rastersoft** [comment]
Ok, added "polkit" and "mimetype". Also added the global version number. Please, check it.

**Comment by cromerc** [comment]
Working correctly in both meson and cmake.

**Comment by rastersoft** [comment]
Great!
