### ISSUE TITLE
Error with include in src

### ISSUE THREAD

**Issue by cromerc** [rastersoft/autovala#88]
I have an include in the src folder which causes this error:
```
CMake Error at src/CMakeLists.txt:146:
  Parse error.  Expected a newline, got identifier with text "include".


-- Configuring incomplete, errors occurred!
See also "/home/cromer/Desktop/projects/pamac-classic/build/CMakeFiles/CMakeOutput.log".
```

The generated CMakeLists.txt has this:
```
install(CODE "MESSAGE (\"
************************************************
* Run 'sudo ldconfig' to complete installation *
************************************************

\") " )include(${CMAKE_CURRENT_SOURCE_DIR}/CMakeSymlinks.txt)
```
As you can see the include is on the same line as the parenthesis. It needs a newline to fix the error.

**Comment by rastersoft** [comment]
Mmm... I see... I'll check the generator.

**Comment by rastersoft** [comment]
Can you put the four previous lines, to have some context?

**Comment by cromerc** [comment]
Here is the CMakeLists.txt in question: https://gist.github.com/cromerc/a14648a453ef37b82b73ebbc563d1bf4

**Comment by rastersoft** [comment]
Ok... It should be fixed now.

**Comment by cromerc** [comment]
Thanks, works great.
