### ISSUE TITLE
Incorrect alias name under meson

### ISSUE THREAD

**Issue by cromerc** [rastersoft/autovala#90]
Using the new alias tag for binaries is not working correctly under meson.
The symlink is created correctly, but it points to the wrong location.

In this case the symlink "pamac-updater" points to "pamac_manager"

As you will notice it is an underscore instead of a dash. The name of the binary is "pamac-manager" not "pamac_manager".

**Comment by rastersoft** [comment]
My fault! Try the code I uploaded a minute ago, it should fix it (and also add support for dbus system service files).

**Comment by cromerc** [comment]
Thanks, now meson has the right target for its symlink.

The new dbus implementation is working and put the service files in the correct place. All that is left is for it to detect the .conf file that is in the data/dbus/ folder and install that into /etc/dbus-1/system.d and then dbus support will complete.

**Comment by rastersoft** [comment]
Working on it. BTW: wouldn't it be better to install the configuration files at share/dbus-1/system.d?

**Comment by rastersoft** [comment]
Done the dbus configuration files. They are installed at share/dbus-1/system.d, but if it is not right, I can change it to /etc/dbus-1/system.d.

Also fixed one of the scripts for installing data with meson. It failed on non-bash shells.

**Comment by cromerc** [comment]
I believe putting it in share/dbus-1/system.d is a better choice. The ones in /usr/share are meant to be "system" configurations while those in /etc are meant to override the ones in /usr/share. I don't know why the original pamac has it in /etc and I don't see any reason to keep it there.

**Comment by rastersoft** [comment]
Great. Then this can be closed.
