### ISSUE TITLE
Incorrect warnings

### ISSUE THREAD

**Issue by cromerc** [rastersoft/autovala#91]
When running autovala update I get this:
```
Updating project file
Warning: Trying to add twice the file src/pamac-tray/tray-appindicator.vala for translation
Warning: Trying to add twice the file src/pamac-tray/tray-gtk.vala for translation
Storing configuration in file /home/cromer/Desktop/projects/pamac-classic/pamac.avprj
Updating CMake files
Warning: Trying to add twice the file src/pamac-tray/tray-appindicator.vala for translation
Warning: Trying to add twice the file src/pamac-tray/tray-gtk.vala for translation
Updating Meson files
Warning: Trying to add twice the file src/pamac-tray/tray-appindicator.vala for translation
Warning: Trying to add twice the file src/pamac-tray/tray-gtk.vala for translation
Done
```

This is caused by doing translations that depend on a build flag:
```
if KDE_TRAY
translate: vala src/pamac-tray/tray-appindicator.vala
else
translate: vala src/pamac-tray/tray-gtk.vala
end
```

There are no problems when building, it builds correctly. Just kind of ugly that it spits out these warnings.

**Comment by rastersoft** [comment]
But you never should use conditionals with "translate". Both source files must be marked for translation always. The "translate" command only specifies that the file must be added to the POTFILES.in file, nothing else, so you should remove that condition.

**Comment by rastersoft** [comment]
Done. Also fixed one of the scripts for installing data with meson. It failed on non-bash shells.

**Comment by cromerc** [comment]
I removed the condition on the translate tags... but autovala re-adds the condition automatically because in my "pamac-try" binary I have this:
```
vala_binary: src/pamac-tray/pamac-tray
version: 6.3.5
vala_local_package: Pamac
if NOT DISABLE_AUR
vala_local_package: AUR
end
vala_package: posix
vala_check_package: json-glib-1.0
vala_check_package: libalpm
vala_check_package: libnotify
if KDE_TRAY
vala_check_package: appindicator3-0.1
else
vala_check_package: gtk+-3.0
end
*vala_check_package: gio-2.0
*vala_check_package: glib-2.0
*vala_check_package: gobject-2.0
if KDE_TRAY
vala_source: tray-appindicator.vala
else
vala_source: tray-gtk.vala
end
*vala_source: alpm_config.vala
*vala_source: pamac_config.vala
*vala_source: tray.vala
```

So the underlying problem is that autovala is putting the condition there.

**Comment by rastersoft** [comment]
Oh! Ok.

**Comment by rastersoft** [comment]
Ok, it should have been fixed in master (and also merged the changes for the dbus config files, I was working in other branch). Edit the .avprj file and remove the conditionals completely (conditionals and the "translate" statements inside), and do an "autovala update".

**Comment by cromerc** [comment]
Yep that fixes the translate conditional problem.

However the dbus config file is not being detected. Is it fully operational? Or are you still working on that?

**Comment by rastersoft** [comment]
It should have been detected... Does the filename end in ".conf"?

**Comment by cromerc** [comment]
The file is data/dbus/org.pamac.system.conf

**Comment by rastersoft** [comment]
My fault, as usual O:) I wasn't storing the statement in the final .avprj file. It should work now. Sorry O:)

**Comment by cromerc** [comment]
Now it is detected, but fails to install.
CMake:
```
CMake Error at data/dbus/cmake_install.cmake:44 (file):
  file INSTALL cannot find
  "/home/cromer/Desktop/projects/pamac-classic/build/data/dbus/org.pamac.system.conf".
Call Stack (most recent call first):
  cmake_install.cmake:45 (include)


FAILED: CMakeFiles/install.util 
cd /home/cromer/Desktop/projects/pamac-classic/build && /usr/bin/cmake -P cmake_install.cmake
ninja: build stopped: subcommand failed.
```
Meson:
```
Meson encountered an error in file meson.build, line 87, column 31:
Expecting lparen got dot.
install_data(dbus_cfg_org.pamac.system.conf,install_dir: join_paths(get_option('prefix'),get_option('datadir'),'dbus-1','system.d'))
```

**Comment by rastersoft** [comment]
Mmm... I'll check it...

**Comment by cromerc** [comment]
Found the problem with cmake:
```
SET(DBUS_PREFIX ${CMAKE_INSTALL_PREFIX})
configure_file(${CMAKE_CURRENT_SOURCE_DIR}/org.pamac.system.service ${CMAKE_CURRENT_BINARY_DIR}/org.pamac.system.service)
install(FILES ${CMAKE_CURRENT_BINARY_DIR}/org.pamac.system.service DESTINATION ${CMAKE_INSTALL_DATAROOTDIR}/dbus-1/system-services/)
configure_file(${CMAKE_CURRENT_SOURCE_DIR}/org.pamac.user.service ${CMAKE_CURRENT_BINARY_DIR}/org.pamac.user.service)
install(FILES ${CMAKE_CURRENT_BINARY_DIR}/org.pamac.user.service DESTINATION ${CMAKE_INSTALL_DATAROOTDIR}/dbus-1/services/)
install(FILES ${CMAKE_CURRENT_BINARY_DIR}/org.pamac.system.conf DESTINATION ${CMAKE_INSTALL_DATAROOTDIR}/dbus-1/system.d/)
```
It is missing the configure_file command.

**Comment by cromerc** [comment]
It looks like meson has 2 problems. It is mising configure_file, and it it has dots in the variable name instead of underscores.

**Comment by rastersoft** [comment]
Fixed. I used part of the code from the other dbus files, but forgot that the config files aren't pre-parsed. What I can't understand is how did it work the test I did...

Anyway, now it seems to work.

**Comment by cromerc** [comment]
Now it works.

**Comment by rastersoft** [comment]
Great. Tagging then and following with more autoconfigurations. Thanks!

**Comment by cromerc** [comment]
No problem, and thanks for all your hard work on autovala, it is a great piece of software.
