### ISSUE TITLE
GSettings schema files

### ISSUE THREAD

**Issue by cromerc** [rastersoft/autovala#94]
It would be nice if autovala could autodetect GSettings schema files, install them to the correct location, and handle the translations with gettext automatically.

I have just started implementing GSettings in my project and am doing this all manually now.

Here is some info on the files: https://wiki.gnome.org/Projects/Vala/GSettingsSample
Here are the schemas I have in my autovala project: https://github.com/cromnix/pamac-classic/tree/dev/data/schemas

**Comment by rastersoft** [comment]
It is already done. The "scheme" statement allows to specify a gsettings file, and files ended in .gschema.xml in the "data" folder will be automagically added.

**Comment by cromerc** [comment]
Woops, didn't notice that one in the docs.
