### ISSUE TITLE
Meson fail to build

### ISSUE THREAD

**Issue by squall77it** [rastersoft/autovala#95]
I have generated meson files for my project with Autovala, but there is a problem.
This is the output I get when trying to build:
```
The Meson build system
Version: 0.45.1
Source dir: /Hackering/My_Project/wifi-qrcode2
Build dir: /Hackering/My_Project/wifi-qrcode2/meson_build
Build type: native build
Project name: wifi-qrcode
Native C compiler: cc (gcc 7.3.0 "cc (Debian 7.3.0-16) 7.3.0")`
Native Vala compiler: valac (valac 0.40.4)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29)
Native dependency gtk+-3.0 found: YES 3.22.29
Native dependency dbus-glib-1 found: YES 0.110
Native dependency gio-2.0 found: YES 2.56.1
Native dependency glib-2.0 found: YES 2.56.1
Native dependency gobject-2.0 found: YES 2.56.1
Program glib-compile-resources found: YES (/usr/bin/glib-compile-resources)
Program /Hackering/My_Project/wifi-qrcode2/meson_scripts/install_data.sh found: YES (/Hackering/My_Project/wifi-qrcode2/meson_scripts/install_data.sh)
Configuring Config.vala using configuration

src/meson.build:28:0: ERROR: File /Hackering/My_Project/wifi-qrcode2/vapis/qrencode.vapi does not exist.

A full log can be found at /Hackering/My_Project/wifi-qrcode2/meson_build/meson-logs/meson-log.txt
```
The problem is that the vapis dir is in src, not in Source dir.
I resolved modifying a line in src/meson.build from:
`wifi_qrcode_sources += [join_paths(meson.source_root(),'vapis/qrencode.vapi')]`
to
`wifi_qrcode_sources += [join_paths(meson.source_root(),'src/vapis/qrencode.vapi')]`

The CMake files work great and everything builds just fine.

**Comment by rastersoft** [comment]
I committed a fix. It was to use "current_source_dir()" instead of "source_root()". It is available here, and now I'm building the debian, ubuntu, fedora and arch packages to upload them to my homepage. Thanks!

**Comment by rastersoft** [comment]
Uploaded. Thanks!

**Comment by squall77it** [comment]
OK now work.
Thanks to you!
