### ISSUE TITLE
autovala/gedit_plugin/src/Config.vala.base does not exist

### ISSUE THREAD

**Issue by staubenheimprobst** [rastersoft/autovala#97]
Hello, 

i have a problem by compile the plugin under Mint 17. 
It does not find the Config.vala.base in the gedit_plugin/src.
I have thise soft linked on Config.vala.base. It this correct so? 

CMake Error: File ~/autovala/gedit_plugin/src/Config.vala.base does not exist
CMake Error at src/CMakeLists.txt:14 (configure_file):
  configure_file Problem configuring file

-- Found Vala: /usr/bin/valac  
-- checking for Vala version of valac-0.30
--   found Vala, version 0.30
-- Found Vala: valac-0.30  
-- Configuring incomplete, errors occurred!

 ~/share/github/autovala/gedit_plugin/src $ ln -s Config.vala.cmake Config.vala.base

**Comment by rastersoft** [comment]
Ops... it seems I forgot to add that file. I uploaded to the repo. Please, do a "git pull" and try again.
